### ISSUE TITLE
Wrong function call

### ISSUE THREAD

**Issue by Ahleroy** [kolappannathan/bootstrap-cookie-banner#9]
I believe there is an issue at this line.

https://github.com/kolappannathan/bootstrap-cookie-banner/blob/6cb3c71025d95df2492bebbb7c5a6bb85f807310/index.html#L62

One should call the function `hideCookieBanner()` instead.

**Comment by kolappannathan** [comment]
@Ahleroy Thank you for rasising the issue. It was supposed to be `cb_hideCookieBanner()`
